development:
  adapter: postgresql
  encoding: unicode
  database: postgres_development
  pool: 5
  username: postgres
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: postgres_test
  pool: 5
  username: postgres
  password:

# production:
#   adapter: postgresql
#   encoding: unicode
#   database: postgres_production
#   pool: 5
#   username: postgres
#   password: